name = "MagneticReadHead"
uuid = "63dd013e-5414-5e51-b21a-a24e12ed54cf"
authors = ["Lyndon White <lyndon.white@invenialabs.co.uk>"]
version = "0.3.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Cassette = "0.2.2"
CodeTracking = "0.5.0"
OrderedCollections = "1.1"
Revise = "2.1.3"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
